### ISSUE TITLE
STL only data

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/Lived-Religion-STL#6]
As this dataset grows and starts to include other regions besides STL, we may need a way to query for data by location.  We have not set this up yet.  In technical terms, there are no properties on data nodes that attribute this data "STL".  If each iteration has a unique access token, then we can use that.  If each iteration will be sharing an access token, we have to add a property to data nodes so each data node knows which iteration it belongs to.

**Comment by cubap** [comment]
This will be solved by the Curation ticket in DEER-LR ([ticket](https://github.com/CenterForDigitalHumanities/deer-LR/issues/203))
